# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 10, 9, 26, 25, 964337, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cover',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 10, 9, 26, 31, 857234, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
