# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 11, 14, 5, 24, 274961, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 11, 14, 5, 29, 856518, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 11, 14, 5, 35, 75310, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 11, 14, 5, 40, 357260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
